### ISSUE TITLE
Adds the subdomain to all links starting with https://discord...

### ISSUE THREAD

**Issue by Teltta** [Luna-devv/rp.replace-discord-link#1]
For example **https://discordpy.readthedocs.io** becomes **https://subdomain.discordpy.readthedocs.io** and **https://discord.js.org/** becomes **https://subdomain.discord.js.org/**.
Somewhat fixed by doing this; https://cdn.discordapp.com/attachments/854729588495220736/1006505916214018079/unknown.png

**Comment by shi-gg** [comment]
Thanks for reporting!
This issue should be fixed with 14e24ac8d8fba4b546b90c02ea6e87a7bbf03c91.
